---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /src
  path: nightwatch

steps:
  - name: test
    image: golang:1.13
    commands:
      - go mod download
      - make test
  - name: build
    image: golang:1.13
    commands:
      - GO111MODULE=off go get github.com/mitchellh/gox
      - make build
    environment:
      BUILD_ARCHS: "linux/amd64 linux/arm64 linux/arm darwin/amd64 windows/amd64"
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - output/*
      draft: true
    checksum:
      - md5
      - sha256
    when:
      event: tag
  - name: docker_amd64
    image: plugins/docker
    settings:
      username: jakolehm
      password:
        from_secret: dockerhub_token
      repo: jakolehm/nightwatch-amd64
      build_args:
        - binary=nightwatch_linux_amd64
  - name: docker_arm4
    image: plugins/docker
    settings:
      username: jakolehm
      password:
        from_secret: dockerhub_token
      repo: jakolehm/nightwatch-arm64
      build_args:
        - binary=nightwatch_linux_arm64
